### ISSUE TITLE
In sipa.js Self is not defined

### ISSUE THREAD

**Issue by alex110414** [magynhard/sipa#6]
![image](https://user-images.githubusercontent.com/42845229/127125521-e1efd107-3b9b-405a-80bb-ab78291c3627.png)

Self is not defined because the "s" in self is uppercase. 
I think it should be: 

`let curr_params = self.getParamsOfUrl(url) ` 

@magynhard what do you think?

**Comment by magynhard** [comment]
@alex110414 thank you for your feedback.

Indeed a typo issue.

Fixed with https://github.com/magynhard/sipa/commit/f42da0d914a5ab94d612ac97cfe509c80a6c2ccc
